Blackduck test cases
synopsys-sig/synopsys-extension pull request #10
Opened 2023-05-08 11:13 UTC by kiransynopsys

2023-05-09 18:20 UTC, kishorikumar requested changes

2023-05-09 18:20 UTC, kishorikumar commented on synopsys-task/src/synopsys-task/application-constant.ts
>  export const COVERITY_USER_PASSWORD_KEY =
Why we have two passphrase related key. Please check, if we are using proper keys which is getting used for coverity.

2023-05-09 18:28 UTC, kishorikumar requested changes

2023-05-10 07:48 UTC, sig-tithi approved these changes

2023-05-10 07:48 UTC, merged