SIGINT-2057, SIGINT-2106:  expose SRM parameters and additional SRM Parameters to be supported
synopsys-sig/synopsys-extension pull request #167
Opened 2024-08-12 05:39 UTC by siyaramsynopsys

2024-08-12 06:06 UTC, maksudur-rahman-maruf commented on synopsys-task/src/synopsys-task/application-constant.ts
> +  "bridge_coverity_execution_path";
For classic editor we are no longer following the snake_case convention.
 Now we are following the camelCase convention. Can you apply the camelCase for all the new fields?

2024-08-12 06:23 UTC, maksudur-rahman-maruf commented on synopsys-task/src/synopsys-task/input.ts
> +function getInputForSrmAssessmentMode() {
I believe the assessment mode is not specified in the SRM requirements. Can you please remove the SRM assessment mode-related code?

2024-08-12 06:44 UTC, maksudur-rahman-maruf commented on synopsys-task/test/unit/synopsys-task/tools-parameter.spec.ts
> +        it('should success for SRM command formation with mandatory parameters', async function () {
Please add a test case for defaulting the project name.

2024-08-12 06:46 UTC, maksudur-rahman-maruf commented on synopsys-task/test/unit/synopsys-task/tools-parameter.spec.ts
> +        it('should success for SRM command formation with mandatory parameters', async function () {
Please add a test case to ensure the project name defaults correctly

2024-08-12 08:09 UTC, maksudur-rahman-maruf commented on synopsys-task/src/synopsys-task/application-constant.ts
> +export const SRM_URL_KEY_CLASSIC_EDITOR = "bridgeSrmUrl";
remove bridge from all the new fields

2024-08-12 08:11 UTC, maksudur-rahman-maruf commented on synopsys-task/src/synopsys-task/model/srm.ts
>    azure?: AzureData;
I think we do not need azure here.

2024-08-12 11:02 UTC, maksudur-rahman-maruf approved these changes

2024-08-12 11:16 UTC, maksudur-rahman-maruf commented on synopsys-task/task.json
> +        "srm": "Software Risk Manager"
Software Risk Manager -> Software Risk Manager (SRM). Please apply this change

2024-08-13 05:30 UTC, zaman-akib requested changes

2024-08-13 05:30 UTC, zaman-akib commented on synopsys-task/src/synopsys-task/validator.ts
> +}
This method can be removed since it has no usage.

2024-08-13 05:30 UTC, zaman-akib commented on synopsys-task/task.json
> +  "description": "Run security scans on Polaris, Black Duck, Coverity or Software Risk Manager platforms",
Add SRM in brackets like  Software Risk Manager (SRM)

2024-08-13 05:30 UTC, zaman-akib commented on vss-extension-dev.json
> +  "description": "Run security scans on Polaris, Black Duck, Coverity or Software Risk Manager platforms",
Add SRM in brackets like Software Risk Manager (SRM)

2024-08-13 05:30 UTC, zaman-akib commented on vss-extension.json
> +  "description": "Run security scans on Polaris, Black Duck , Coverity or Software Risk Manager platforms",
Add SRM in brackets like Software Risk Manager (SRM)

2024-08-13 05:30 UTC, zaman-akib commented on synopsys-task/src/synopsys-task/tools-parameter.ts
> +    const inputJson = JSON.stringify(srmData);
to filter the empty data use the method `filterEmptyData()` before preparing json.

```
// Remove empty data from json object
srmData = filterEmptyData(srmdata);
```

2024-08-13 06:06 UTC, zaman-akib approved these changes

2024-08-13 06:08 UTC, spurohitsynopsys commented on synopsys-task/src/synopsys-task/model/srm.ts
> +  coverity?: coverityDetails;
Can you rename coverityDetails to CoverityDetails to follow consistent naming conventions across all.

2024-08-13 06:15 UTC, spurohitsynopsys commented on synopsys-task/src/synopsys-task/synopsys-bridge.ts
> +    const commandFormatter = new SynopsysToolsParameter(tempDir);
maybe we can move` const commandFormatter = new SynopsysToolsParameter(tempDir);` into if block after L219

2024-08-13 12:41 UTC, spurohitsynopsys approved these changes

2024-08-14 08:59 UTC, merged